### ISSUE TITLE
为啥去掉face_recognition的py后缀

### ISSUE THREAD

**Issue by steinvenic** [coderXuXiang/Face_Recognition#1]
没接触过这样的项目，调了半天的face_detection.py文件，就是不出标记，原来是要运行face_recognition啊。。。。。

**Comment by coderXuXiang** [comment]
face_detection文件是人脸检测，只需要检测人脸就行，face_recognition是人脸识别，在人脸检测的基础上识别是谁的脸。我在readMe文件中有说明，可能是文件说明不太显眼的缘故吧。

**Comment by steinvenic** [comment]
感谢回复，我在研究一下
